/**
 * Standardized Error Codes
 * 
 * Format: ERR_<CATEGORY>_<DETAIL>
 * - Deterministic
 * - Machine-parsable
 * - Localizable
 * - Audit-log safe
 * - No internal stack traces
 */
export enum ErrorCode {
  // Authentication & Operator Errors
  ERR_AUTH_INVALID_TOKEN = 'ERR_AUTH_INVALID_TOKEN',
  ERR_AUTH_OPERATOR_BLOCKED = 'ERR_AUTH_OPERATOR_BLOCKED',
  ERR_AUTH_IP_NOT_ALLOWED = 'ERR_AUTH_IP_NOT_ALLOWED',
  ERR_AUTH_SIGNATURE_INVALID = 'ERR_AUTH_SIGNATURE_INVALID',
  ERR_AUTH_EXPIRED = 'ERR_AUTH_EXPIRED',

  // Round State Errors
  ERR_ROUND_NOT_FOUND = 'ERR_ROUND_NOT_FOUND',
  ERR_ROUND_CLOSED = 'ERR_ROUND_CLOSED',
  ERR_ROUND_SETTLED = 'ERR_ROUND_SETTLED',
  ERR_ROUND_NOT_STARTED = 'ERR_ROUND_NOT_STARTED',
  ERR_ROUND_RESULT_PENDING = 'ERR_ROUND_RESULT_PENDING',

  // Bet Validation Errors
  ERR_BET_AMOUNT_TOO_LOW = 'ERR_BET_AMOUNT_TOO_LOW',
  ERR_BET_AMOUNT_TOO_HIGH = 'ERR_BET_AMOUNT_TOO_HIGH',
  ERR_BET_LIMIT_EXCEEDED = 'ERR_BET_LIMIT_EXCEEDED',
  ERR_BET_DUPLICATE = 'ERR_BET_DUPLICATE',
  ERR_BET_SELECTION_INVALID = 'ERR_BET_SELECTION_INVALID',
  ERR_BET_SELECTION_COUNT = 'ERR_BET_SELECTION_COUNT',
  ERR_BET_SELECTION_RANGE = 'ERR_BET_SELECTION_RANGE',
  ERR_BET_SELECTION_DUPLICATE = 'ERR_BET_SELECTION_DUPLICATE',
  ERR_BET_MAX_WIN_EXCEEDED = 'ERR_BET_MAX_WIN_EXCEEDED',

  // Wallet Errors
  ERR_WALLET_INSUFFICIENT_FUNDS = 'ERR_WALLET_INSUFFICIENT_FUNDS',
  ERR_WALLET_TIMEOUT = 'ERR_WALLET_TIMEOUT',
  ERR_WALLET_REJECTED = 'ERR_WALLET_REJECTED',
  ERR_WALLET_ROLLBACK_FAILED = 'ERR_WALLET_ROLLBACK_FAILED',

  // System Errors
  ERR_SYSTEM_INTERNAL = 'ERR_SYSTEM_INTERNAL',
  ERR_SYSTEM_MAINTENANCE = 'ERR_SYSTEM_MAINTENANCE',
  ERR_SYSTEM_RATE_LIMIT = 'ERR_SYSTEM_RATE_LIMIT',
  ERR_SYSTEM_FRAUD_SUSPECTED = 'ERR_SYSTEM_FRAUD_SUSPECTED',
}
